// src/models/TalentModel.ts

export interface Talent {
    id?: number; // Optional because it will be auto-generated by the database
    name: string;
    talentName: string;
    institutionName: string;
    talentType: string;
    email: string;
    contactNumber: string;
    description: string;
    attachment: string; // File path where the attachment is stored
  }
  